@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title C3 Component: Analyzer Service

Container_Boundary(analyzer, "Analyzer Service") {
    Component(router, "HTTP Router", "Golang", "Маршрутизация HTTP")

    Component(handlers, "API Handlers", "Golang", "REST-контроллеры")

    Component(analytics_service, "Analytics Service", "Golang", "Бизнес-логика вычисления аналитических метрик")

    Component(postgres_repo, "PostgreSQL Repository", "Golang, pgx", "Чтение сырых данных по задачам")
}

Container(gateway, "Gateway Service", "Golang", "Обрабатывает запросы")
ContainerDb(postgres, "PostgreSQL", "SQL Database", "Хранит сырые данные по задачам")

Rel_R(gateway, router, "REST API", "Запрос аналитики")
Rel_D(router, handlers, "", "Передача запросов")

Rel_D(handlers, analytics_service, "", "Запрос вычисления метрик")

Rel_D(analytics_service, postgres_repo, "", "Чтение сырых данных")

Rel_L(postgres_repo, postgres, "SQL", "SELECT")

@enduml
