@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title C3 Component: Gateway Service

Container_Boundary(gateway, "Gateway Service") {
    Component(server, "HTTP Server", "Gin / chi", "Принимает входящие REST запросы")
Component(handlers, "Handlers", "Golang", "Обработчики REST эндпоинтов")
    Component(connector_client, "Connector gRPC Client", "Golang / gRPC", "Запрашивает заголовки и описания проектов")
    Component(analyzer_client, "Analyzer gRPC Client", "Golang / gRPC", "Запрашивает аналитические данные")
    Component(amqp_publisher, "AMQP Publisher", "Golang / AMQP", "Публикует команды на загрузку/обновление данных")
}

Container(webapp, "Web Application", "Angular", "SPA")
Container(analyzer, "Analyzer Service", "Golang", "Сервис для вычисления аналитических данных")
Container(connector, "Connector Service", "Golang", "Сервис по получению данных из Jira")
ContainerQueue(queue, "RabbitMQ", "Broker/Queue", "Используется для межсервисного взаимодействия")

Rel(webapp, server, "Запросы данных и команды", "HTTPS / REST")
Rel(server, handlers, "Передаёт запрос")
Rel(handlers, connector_client, "Запрос заголовков/описаний проектов")
Rel(handlers, analyzer_client, "Запрос аналитики")
Rel(handlers, amqp_publisher, "Команда на загрузку/обновление")
Rel(connector_client, connector, "gRPC")
Rel(analyzer_client, analyzer, "gRPC")
Rel(amqp_publisher, queue, "AMQP")

@enduml
